// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.4.0
// source: calculation.proto

package pb

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type CalculationRequestBody struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Origin string   `protobuf:"bytes,1,opt,name=origin,proto3" json:"origin,omitempty"`
	Cities []string `protobuf:"bytes,2,rep,name=cities,proto3" json:"cities,omitempty"`
}

func (x *CalculationRequestBody) Reset() {
	*x = CalculationRequestBody{}
	if protoimpl.UnsafeEnabled {
		mi := &file_calculation_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CalculationRequestBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculationRequestBody) ProtoMessage() {}

func (x *CalculationRequestBody) ProtoReflect() protoreflect.Message {
	mi := &file_calculation_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculationRequestBody.ProtoReflect.Descriptor instead.
func (*CalculationRequestBody) Descriptor() ([]byte, []int) {
	return file_calculation_proto_rawDescGZIP(), []int{0}
}

func (x *CalculationRequestBody) GetOrigin() string {
	if x != nil {
		return x.Origin
	}
	return ""
}

func (x *CalculationRequestBody) GetCities() []string {
	if x != nil {
		return x.Cities
	}
	return nil
}

type CalculationResponseBody struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cities        []string `protobuf:"bytes,1,rep,name=cities,proto3" json:"cities,omitempty"`
	TotalDistance int32    `protobuf:"varint,2,opt,name=total_distance,json=totalDistance,proto3" json:"total_distance,omitempty"`
	Error         string   `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *CalculationResponseBody) Reset() {
	*x = CalculationResponseBody{}
	if protoimpl.UnsafeEnabled {
		mi := &file_calculation_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CalculationResponseBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculationResponseBody) ProtoMessage() {}

func (x *CalculationResponseBody) ProtoReflect() protoreflect.Message {
	mi := &file_calculation_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculationResponseBody.ProtoReflect.Descriptor instead.
func (*CalculationResponseBody) Descriptor() ([]byte, []int) {
	return file_calculation_proto_rawDescGZIP(), []int{1}
}

func (x *CalculationResponseBody) GetCities() []string {
	if x != nil {
		return x.Cities
	}
	return nil
}

func (x *CalculationResponseBody) GetTotalDistance() int32 {
	if x != nil {
		return x.TotalDistance
	}
	return 0
}

func (x *CalculationResponseBody) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_calculation_proto protoreflect.FileDescriptor

var file_calculation_proto_rawDesc = []byte{
	0x0a, 0x11, 0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0x48, 0x0a, 0x16, 0x43, 0x61, 0x6c, 0x63, 0x75,
	0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x42, 0x6f, 0x64,
	0x79, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x69, 0x74,
	0x69, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x63, 0x69, 0x74, 0x69, 0x65,
	0x73, 0x22, 0x6e, 0x0a, 0x17, 0x43, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x6f, 0x64, 0x79, 0x12, 0x16, 0x0a, 0x06,
	0x63, 0x69, 0x74, 0x69, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x63, 0x69,
	0x74, 0x69, 0x65, 0x73, 0x12, 0x25, 0x0a, 0x0e, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x64, 0x69,
	0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0d, 0x74, 0x6f,
	0x74, 0x61, 0x6c, 0x44, 0x69, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x32, 0x67, 0x0a, 0x12, 0x43, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x51, 0x0a, 0x14, 0x43, 0x61, 0x6c, 0x63, 0x75,
	0x6c, 0x61, 0x74, 0x65, 0x4f, 0x70, 0x74, 0x69, 0x6d, 0x61, 0x6c, 0x50, 0x61, 0x74, 0x68, 0x12,
	0x1a, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x42, 0x6f, 0x64, 0x79, 0x1a, 0x1b, 0x2e, 0x70, 0x62,
	0x2e, 0x43, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x42, 0x6f, 0x64, 0x79, 0x22, 0x00, 0x42, 0x04, 0x5a, 0x02, 0x70, 0x62,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_calculation_proto_rawDescOnce sync.Once
	file_calculation_proto_rawDescData = file_calculation_proto_rawDesc
)

func file_calculation_proto_rawDescGZIP() []byte {
	file_calculation_proto_rawDescOnce.Do(func() {
		file_calculation_proto_rawDescData = protoimpl.X.CompressGZIP(file_calculation_proto_rawDescData)
	})
	return file_calculation_proto_rawDescData
}

var file_calculation_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_calculation_proto_goTypes = []interface{}{
	(*CalculationRequestBody)(nil),  // 0: pb.CalculationRequestBody
	(*CalculationResponseBody)(nil), // 1: pb.CalculationResponseBody
}
var file_calculation_proto_depIdxs = []int32{
	0, // 0: pb.CalculationService.CalculateOptimalPath:input_type -> pb.CalculationRequestBody
	1, // 1: pb.CalculationService.CalculateOptimalPath:output_type -> pb.CalculationResponseBody
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_calculation_proto_init() }
func file_calculation_proto_init() {
	if File_calculation_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_calculation_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CalculationRequestBody); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_calculation_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CalculationResponseBody); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_calculation_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_calculation_proto_goTypes,
		DependencyIndexes: file_calculation_proto_depIdxs,
		MessageInfos:      file_calculation_proto_msgTypes,
	}.Build()
	File_calculation_proto = out.File
	file_calculation_proto_rawDesc = nil
	file_calculation_proto_goTypes = nil
	file_calculation_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// CalculationServiceClient is the client API for CalculationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CalculationServiceClient interface {
	CalculateOptimalPath(ctx context.Context, in *CalculationRequestBody, opts ...grpc.CallOption) (*CalculationResponseBody, error)
}

type calculationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCalculationServiceClient(cc grpc.ClientConnInterface) CalculationServiceClient {
	return &calculationServiceClient{cc}
}

func (c *calculationServiceClient) CalculateOptimalPath(ctx context.Context, in *CalculationRequestBody, opts ...grpc.CallOption) (*CalculationResponseBody, error) {
	out := new(CalculationResponseBody)
	err := c.cc.Invoke(ctx, "/pb.CalculationService/CalculateOptimalPath", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CalculationServiceServer is the server API for CalculationService service.
type CalculationServiceServer interface {
	CalculateOptimalPath(context.Context, *CalculationRequestBody) (*CalculationResponseBody, error)
}

// UnimplementedCalculationServiceServer can be embedded to have forward compatible implementations.
type UnimplementedCalculationServiceServer struct {
}

func (*UnimplementedCalculationServiceServer) CalculateOptimalPath(context.Context, *CalculationRequestBody) (*CalculationResponseBody, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CalculateOptimalPath not implemented")
}

func RegisterCalculationServiceServer(s *grpc.Server, srv CalculationServiceServer) {
	s.RegisterService(&_CalculationService_serviceDesc, srv)
}

func _CalculationService_CalculateOptimalPath_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CalculationRequestBody)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalculationServiceServer).CalculateOptimalPath(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.CalculationService/CalculateOptimalPath",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalculationServiceServer).CalculateOptimalPath(ctx, req.(*CalculationRequestBody))
	}
	return interceptor(ctx, in, info, handler)
}

var _CalculationService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.CalculationService",
	HandlerType: (*CalculationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CalculateOptimalPath",
			Handler:    _CalculationService_CalculateOptimalPath_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "calculation.proto",
}
